version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - keycloak_postgres:/data/postgres
      - ./src/main/resources/sql-scripts/keyCloakDBDump.sql:/docker-entrypoint-initdb.d/keyCloakDBDump.sql
    ports:
      - 5434:5432
    networks:
      - secureClientNetwork

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "5435:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - secureClientNetwork

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    ports:
      - 8081:8081
    command:
      - "start-dev"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloakdb?currentSchema=keycloak
      KC_DB_DATABASE: keycloakdb
      KC_DB_SCHEMA: keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KEYCLOAK_USER: user
      KEYCLOAK_PASSWORD: user
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: keycloak
      KC_HTTP_PORT: 8081
    networks:
      - secureClientNetwork
    depends_on:
      - postgres

  auth-service:
    build: .
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_SERVER_URL=http://keycloak:8081
      - KEYCLOAK_REALM=secure-client-realm
      - KEYCLOAK_ADMIN_CLIENT_ID=admin-cli
      - KEYCLOAK_ADMIN_CLIENT_SECRET=OqLClRwwwMtROz8VQftySuDVk7sj2mW1
      - KEYCLOAK_CLIENT_ID=auth-service
    networks:
      - secureClientNetwork
    depends_on:
      - keycloak
networks:
  secureClientNetwork:
    driver: bridge

volumes:
  keycloak_postgres:
  pgadmin-data:

