keycloak:
  server-url: http://localhost:8081
  realm: secure-client-realm
  admin-Client-Id: admin-cli
  admin-client-secret: OqLClRwwwMtROz8VQftySuDVk7sj2mW1
  client-id: auth-service

spring:
  application:
    name: authService
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8081/realms/${keycloak.realm}
server:
  port: 8080
logging:
  level:
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
